"""initial migration

Revision ID: f930e84e9aca
Revises: 
Create Date: 2023-10-31 13:57:01.020352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f930e84e9aca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keeper_chain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('crypto_asset_score', sa.Integer(), nullable=True),
    sa.Column('last_updated_coingecko', sa.DateTime(), nullable=True),
    sa.Column('coingecko_id', sa.String(), nullable=True),
    sa.Column('ftm_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keeper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['keeper_chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('circulating_supply', sa.Float(), nullable=True),
    sa.Column('burned', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('staked_lp', sa.Float(), nullable=True),
    sa.Column('staked_x', sa.Float(), nullable=True),
    sa.Column('treasury', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('volume_24h_usd', sa.Float(), nullable=True),
    sa.Column('tvl_usd', sa.Float(), nullable=True),
    sa.Column('fdv_1y', sa.Float(), nullable=True),
    sa.Column('fdv_2y', sa.Float(), nullable=True),
    sa.Column('fdv_5y', sa.Float(), nullable=True),
    sa.Column('fdv_10y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keeper_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('keeper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keeper_id'], ['keeper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keeper_balance')
    op.drop_table('metrics')
    op.drop_table('keeper')
    op.drop_table('token')
    op.drop_table('keeper_chain')
    # ### end Alembic commands ###
